### ISSUE TITLE
records from nkn-dev need made visible to frontend by migrating the nkn-dev db to nknportal-dev

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#110]
right now these are not visible in https://nkn-dev.nkn.uidaho.edu/metadata or on production

**Comment by mguarinello** [comment]
@mtpain located these, but still aren't showing up in the frontend

**Comment by mtpain** [comment]
masqueraded as users who had records on first prototype on nkn-dev and records seem to be there and intact.
