### ISSUE TITLE
help video for metadata editor

### ISSUE THREAD

**Issue by mtpain** [northwest-knowledge-network/mdedit#131]

**Comment by ccasey645** [comment]
hindsjj and I made an automated tutorial that might replace the help video. It can be seen on the stepUI branch by clicking on the "Step X" buttons next to the list of steps at the top of the screen.

**Comment by ccasey645** [comment]
I believe this feature has been supplanted by the form wizard version of the Metadata editor. Thoughts?

**Comment by hindsjj** [comment]
I agree -- the new MD editor wizard is much easier to navigate.  A help video may no longer be necessary.
