### ISSUE TITLE
Not getting username in /app/api/views.py

### ISSUE THREAD

**Issue by flathers** [northwest-knowledge-network/mdedit#135]
In the 'publish_metadata_record' function, I try to get the username using the same function call used elsewhere in views.py, but what I end up with is 'local_user' as the username.  I'm guessing something about the request object isn't working at that point, but I'm not sure why.  How can we pass usernames into gptInsert from views.py?

**Comment by ccasey645** [comment]
If the Angular app is not hosted in Drupal (I.E. the Angular app is being hosted on a local machine), then the session_id returned from the Angular factory is "local" (https://github.com/northwest-knowledge-network/mdedit/blob/master/frontend/js/services.js : function starting on line 6). So, in the request object in views.py, the _authenticate_user_from_session function returns "local_user" if the response object's session_id is "local." 

Also, there is a bit of code in frontend/js/services.js: line 518 AttachmentService that is commented out in the copy I recently cloned from the master branch, but basically there are two blocks of code (one uncommented, one commented with a note before both of them) that will either make the url in the http.post either "http://localhost:4000/api/upload" or "https://nknportal-dev.nkn.uidaho.edu/portal/simpleUpload/upload.php". In the Flask Python app, line 216 of app/api/views.py checks if the request.base_url contains "localhost". If it does not, then it calls the gptInsert.gptInsertRecord function. So, in frontend/js/services.js, in the AttachmentService service function (line 518), which block of code is commented out? I'm thinking if you change which block is commented out this will help. 

Or possibly using the development server that was set up recently will sidestep the localhost issue completely?

**Comment by flathers** [comment]
One detail that I should have mentioned in my first comment: I was doing this from a Drupal hosted installation of the software, and it worked correctly other than this (it clearly got my username correctly to show me the list of records I own), so it seems like there's something wrong with the way I'm calling the function that returns username.  My suspicion is that the request object is out of scope, or the request is not coming from the place I expected, or something like that.

**Comment by ccasey645** [comment]
I think I've fixed this, but I'm not exactly sure how to test it. I don't think that this functionality is ever tested in the e2e tests, which would make sense why we haven't found it until now. And I believe that the development server does not have the capability to publish a record, which is when this function is called.

**Comment by ccasey645** [comment]
Tested by printing the username variable in line 218 of app/api/views.py. Before, the session ID was not being passed into the publish record route from the frontend, so the authentication function didn't have a session_id to use to authenticate correctly.
