### ISSUE TITLE
dateStamp on ISO metadata

### ISSUE THREAD

**Issue by flathers** [northwest-knowledge-network/mdedit#143]
The date stamp of records exported from mdedit as ISO aren't valid under the ISO schema.  The date stamp is written out at the xpath "/gmi:MI_Metadata/gmd:dateStamp/gco:Date"
With content, for example, "2016-10-19 07:05 PM GMT"

So two things: 
First, if we want time in there, then we should be writing to xpath "/gmi:MI_Metadata/gmd:dateStamp/gco:DateTime"
And second, the content needs to be a properly formed ISO 8601 date time, which means it should look something like "2016-10-19T19:05:00Z" or "2016-10-19T19:05:00+00:00"

There's a pretty good ISO 8601 reference on wikipedia: https://en.wikipedia.org/wiki/ISO_8601

**Comment by ccasey645** [comment]
Oddly enough, the publish date stored in the MongoDB is in ISO format already (EX: 2016-10-13T07:00:00Z). I've tested retrieving this value from the database and printing it in the review page, and it is still in ISO format there too, so the middleware is not converting the format either. For some reason the XSLT file is converting the format to a non-ISO format. I'm looking in to why this is happening, and will be making a new branch called dateStampFix to address this problem.

**Comment by ccasey645** [comment]
Actually it was the middleware: app/api/views.py had a time formatting function that was not set to the ISO standard. So while the date was stored in the database as the ISO format, it was being converted to a different format when the XSLT was generated by the python backend. 

I will make a pull request of the dateStampFix branch into master today that includes the fixed code.

**Comment by flathers** [comment]
One question... have you updated the XSLT with the "DateTime" element name instead of "Date"?

**Comment by ccasey645** [comment]
Yes I did.
