### ISSUE TITLE
URL's being added multiple times for each Data Access Contact

### ISSUE THREAD

**Issue by ccasey645** [northwest-knowledge-network/mdedit#148]
Discovered a bug where the XSLT's in the metadata editor are adding the "online" url from the record, and the gemerated XML download urls for each Data Access Contact. So if there are 2 Data Access Contacts, then the "online" url and the XML download url will appear 2 times each, for a total of 4 links. And those links should only be in the XML file once each.

Need to fix this because the multiple links are being interpreted by the XSLT's in the Data Search page as discrete links, so each link appears multiple times.

**Comment by flathers** [comment]
This is the same as, or at least closely related to, #145.

**Comment by ccasey645** [comment]
Yeah I just realized that 😆
