### ISSUE TITLE
Research Methods Not Added to XML

### ISSUE THREAD

**Issue by ccasey645** [northwest-knowledge-network/mdedit#150]
When a record is published, the XML generator in the Python backend is not using the "research_methods" attribute from the MongoDB record. We added this attribute, but forgot to put it into the generated XML. I can add this attribute to the XML quite easily, but am unsure of where in the XML it should go.

Also, the XSLT used for the search page might need to be updated if the "research_methods" is something we want people searching records to easily see. However, this attribute can be very long so it would probably take up too much info on the search page, in my opinion.

**Comment by flathers** [comment]
The most appropriate place is probably in the data quality section as a process step.  The data quality section must immediately follow the distribution information section.  Here is a minimal example of a data quality section with lineage populated from the database:
```xml
<gmd:dataQualityInfo>
  <gmd:DQ_DataQuality>
    <gmd:scope>
      <gmd:DQ_Scope>
        <gmd:level>
          <gmd:MD_ScopeCode codeList="http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#MD_ScopeCode" codeListValue="dataset">dataset</gmd:MD_ScopeCode>
        </gmd:level>
      </gmd:DQ_Scope>
    </gmd:scope>
    <gmd:lineage>
      <gmd:LI_Lineage>
        <gmd:processStep>
          <gmd:LI_ProcessStep>
            <gmd:description>
              <gco:CharacterString><xsl:value-of select="/root/record/research_methods"/></gco:CharacterString>
            </gmd:description>
          </gmd:LI_ProcessStep>
        </gmd:processStep>
      </gmd:LI_Lineage>
    </gmd:lineage>
  </gmd:DQ_DataQuality>
</gmd:dataQualityInfo>
```
