### ISSUE TITLE
remove link doesn't delete file

### ISSUE THREAD

**Issue by flathers** [northwest-knowledge-network/mdedit#152]
In the 'Upload File' tab of mdedit, once I've chosen and attached a file, the file is uploaded to the server and sits within the record's subdirectory.  If I then click the 'remove' link next to the file, a DELETE request is made and returns HTTP 200/OK, but the file is still in the subdirectory.  I haven't tested publication, but I'd assume that the file gets published with everything else in the subdirectory when the record is published.

And I just noticed why this is happening--uploaded data is posted to nknportal-dev, but DELETE requests are made to nknportal-prod.  So I'd guess that this is related to #138.

**Comment by ccasey645** [comment]
Fixed in newest version.
