### ISSUE TITLE
Can't delete contacts

### ISSUE THREAD

**Issue by flathers** [northwest-knowledge-network/mdedit#153]
On the contacts tab, there is no way to delete existing authors or data access contacts.  This is especially evident if you accidentally click either 'Add an Author' or 'Add an Access Contact' and then go to another tab; when you return to contacts, you will have a blank contact record that the 'Cancel x Add' button cannot remove.  Maybe instead of a single cancel button, put an X button on each contact that will remove it from the record?

**Comment by ccasey645** [comment]
It seems that when a contact is first added, if the user does not put in anything in to the form inputs, the contact can be removed. But after the first character is typed and the record is saved, then the system cannot remove the erroneous contact.

**Comment by ccasey645** [comment]
After investigating the controllers.js code, I found a part of the code that only allows the contacts to be deleted before the record is saved to the database. I'm not sure why this was added to the system, but it has been removed, and all the end to end tests still pass. 

I'm not sure why this was added to the system, but it does not give the functionality we want.

**Comment by ccasey645** [comment]
I've fixed this issue in commit ca421b03be9e5ce1535d73410c8f32e85c180d9b. Merged in to master, and needs to be deployed to production.
