### ISSUE TITLE
Project Defaults

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#2]
For future applications

Create a way to have users select a NKN supported project (from a dropdown list or select a circle/box next to project name, listed across top of editor) they are contributing metadata to. Once selected, the editor will automatically populate fields with appropriate defaults for the project. Some of these defaults may be hidden to the user, others will be displayed and will be editable by the user, some will be displayed but not editable. For example, MILES keywords will be displayed so that the user will not enter them and result in duplicates, but the user will not be able to edit them because they need to remain part of the metadata.
Current fields that have defaults for MILES are: 
State and Country in Address block (viewable, editable)
Thematic Keywords (viewable, not editable)
Place Keywords (viewable, not editable)
Use & Access Restrictions (viewable, editable)
License (viewable, editable)
Spatial Extent (viewable, editable)

**Comment by mguarinello** [comment]
We can hard code these in the XSLT so they will be in the output ISO xml.

We can probably use the XSLT to indicate IF  "Use MILES defaults" is selected to add certain values. I am not sure of the mechanisms for this yet.

**Comment by mtpain** [comment]
Discussed at weekly meeting, will do autopopulate on the front end to start and possibly in the future.
