### ISSUE TITLE
Add instructions based on Design Document

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#20]
Create instructions for each field or group of fields based on the information in the column "Form Field Guiding Questions & Text" in the Excel design document.

These should not be 'hover help' but appear as text on the form.

**Comment by mguarinello** [comment]
This is done for existing fields, but will need to be edited with enhancements and as new fields are added. Keep open?

**Comment by mtpain** [comment]
Hm.. let's close so that we get a feel for cycle time. In the future let's
not consider new fields complete until they have both a UI element and
accompanying instruction.

**Comment by mguarinello** [comment]
sounds great.
