### ISSUE TITLE
make submission contingent on filling in required fields

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#29]
Most field will be required, some are optional (refer to design doc)
users should not be able to submit as final if required fields are empty or not valid. They should be able to save and return to their work later.

**Comment by mtpain** [comment]
This is really two issues. "Save and return to their work" is separate and a bit more complicated, and I'd guess a little less of a priority?

**Comment by mguarinello** [comment]
This is now complete. Closing.
