### ISSUE TITLE
NKN Contact as Distributor - Opt in or out

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#3]
Slightly different than other address blocks I think, because NKN's as contact entity has a uuid (distributor component https://www.northwestknowledge.net/iso/components/390bb26a-184d-4c30-8b3e-d74fe0783e28.xml) includes the following in the iso xml:
<gmd:distributorContact xlink:title="NKN">
            <gmd:CI_ResponsibleParty uuid="390bb26a-184d-4c30-8b3e-d74fe0783e28">

Function:
Present users with the option:
"Are you storing your data with NKN?" 
If user selects Yes, then the editor will insert the NKN distributor code block into the output xml. If the user selects No, the regular contact fields be added to online editor for user to fill out.

**Comment by mtpain** [comment]
This is great. In the future or for a wider audience to maybe use this, we want to think about how to generalize this so that there is a default data distributor.

**Comment by mguarinello** [comment]
We also need to make sure this is just an opt-in. We hope that most people who use our editor will also store their data with NKN. But that may not be the case all the time.

**Comment by mguarinello** [comment]
Revising:  Need to have "Are you storing your Data with NKN?" And then have a check box for Yes and for No.
If Yes, additional data fields should appear for Online Resource Links to be used for NKN, or Access Contact 1 can be filled in with NKN information, and only the Online Resource Link made editable.

Once this features is enabled, we will need to edit the instructions to read, "If you are not storing your data with NKN or are storing it in additional repositories, please provide contact information here."

**Comment by mguarinello** [comment]
load NKN as default in cleanup PR
