### ISSUE TITLE
Add field for data format; also need values for dropdown list

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#30]
Add field for data format
Need input from Ed on good list of this
Will be dropdown, plus an option to write it
And allow multiple entries.

**Comment by mtpain** [comment]
@flathers @mguarinello Let's get those values by mid next week when I'll try to roll through the issues in the "Second round" milestone

**Comment by mguarinello** [comment]
Here is a preliminary list @flathers  please add anything I am missing here. In alphabetical order.
The field needs to be dropdown with multiple selection (like Topic Category) and have an option to write in values that aren't in the list.
﻿Values for List: ASCII, csv, DLG, docx, DRG, DWG, eps, ERDAS, Esri grid, Esri TIN, FASTA, FASTQ, GenBank, GeoJSON, GeoTIFF, GML, HDF, jpeg, KML, LAS, mp3, MrSID, netCDF, pdf, php, png, py, R, SDXF, Shapefile, SPSS, Stata, Tab, tiff, txt, VBS, wav, xls, xlsx, xml

**Comment by mguarinello** [comment]
See #37 for info about where to put this field in the layout. Thanks!

**Comment by flathers** [comment]
One thing about this: when you specify a data format name, you are also required to specify a data format version.  This can quickly get messy (who knows off the top of their head what version of .tiff they're using?).  You could get around this by using <gmd:version gco:nilReason="missing" /> to express the fact that there probably is a format version, but we don't know what it is.

**Comment by mguarinello** [comment]
Thanks for the info @flathers. I didn't realize the version was a required element if format was listed. How do we express that we don't know what the format is in the XML record? Is this one where there is a code for "nilReason"?

**Comment by mguarinello** [comment]
@flathers Is the specification field also required when we add data format? Is there a similar work-around?

**Comment by flathers** [comment]
Specification is totally optional, so no need to worry about it.

On Fri, Jul 17, 2015 at 9:18 AM, Marisa Guarinello <notifications@github.com

**Comment by mguarinello** [comment]
Addressed in pull request #55 and in XSLT
