### ISSUE TITLE
Confusion on Dates

### ISSUE THREAD

**Issue by mtpain** [northwest-knowledge-network/mdedit#35]
At one point, I believe the data published date was called "First Published Date". The title in the design doc seems to now be "Date (dataset)". In #34 I made the title a little more descriptive "Data Publish Date" and included the Guiding Questions & Text as written in the design doc. 

What should be the final name of the field? Fine by me if we just go with "Date (dataset)" like it says in the design doc.

**Comment by mguarinello** [comment]
Thanks for the clarifying question. Please use Date (dataset) and include the Guiding Questions and Text. It can be date the data was published or updated for I want to keep publish out of the field label.

Thanks!
