### ISSUE TITLE
Add option to finalize a metadata record and publish to NKN Portal

### ISSUE THREAD

**Issue by mtpain** [northwest-knowledge-network/mdedit#36]
@flathers @mguarinello, we'll have to discuss this one. Please add details to this issue as you see fit.

**Comment by flathers** [comment]
There is a kind of prototype for this in the code that ingests data into the portal from the upload tool.  It's all written in Java, so it will have to be converted to Python.  I believe that this task will be *much* easier to do toward the end of the summer, when Geoportal doesn't have to be involved.  So if we can wait that long, that would be great.  If we can't, then we can work on porting the Java code.

**Comment by mguarinello** [comment]
@flathers Yes, I think we can wait until we no longer have to involve Geoportal for this item. This goes for all issues in the Portal Integration milestone.

**Comment by mguarinello** [comment]
option is now available through nkn-dev
@flathers set up to work.
admin workflow still needed
