### ISSUE TITLE
Create option for loading a program default, use MILES as test case

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#38]
Enable a dropdown option for users to allow them to select a project and then have default values loaded into the editor. The interface might say "Are you submitting data related to an NKN-supported project? Select your project here to load default values into the template." This type of set-up would be easily expandable as we offer metadata support for large projects in the future.

The kinds of things we would load into defaults would be the grant number of a keyword (this is important for any special searching we want to enable, as on the MILES idahoecosystems.org data page), and particular access and use constraints related to the grant, for example, EPSCoR has boilerplate language that needs to be use.

We could create a default_miles.json file to start the testing of this.

I am willing to reassign this to myself with a few pointers on how to implement.

**Comment by mtpain** [comment]
You could go ahead and create a new branch for this with a default_miles.json and push to origin and we can go from there. Create a new directory `frontend/static/default_metadata` and put it there. Start from the current master branch. We can merge updated masters into your defaults branch when we finish our pull request, or you could just wait until we finish our big merge (hopefully tomorrow?)

**Comment by mguarinello** [comment]
I will wait until after big merge. I hope tomorrow too!


Marisa Guarinello
Environmental Data Manager
MILES EPSCoR Project
Northwest Knowledge Network
University of Idaho, Office of Research & Economic Development
mguarinello@uidaho.edu
208-885-5044

**Comment by mguarinello** [comment]
Closing this issue. Will make a new branch this week.
