### ISSUE TITLE
Create uuid for metadata record in generic /xml resource

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#4]
The metadata editor needs to create a unique identifier for each metadata record and output this to the editor-generate xml. This will populate the <gmd:file identifier> component in the ISO xml.
This may also be useful somehow in the Edit functionality needed for when the user needs to retrieve a metadata record to edit.

**Comment by mtpain** [comment]
This should be fine. There is already an ID so that users can edit the record that's stored in the database, but it's just a positive integer. You're saying there's a required ISO field that needs a proper UUID?

**Comment by mguarinello** [comment]
Yes, I think so. In the Challis Lidar ISO metadata that is a good source example the file uuid and dataset uuid are the same and I believe refer to the folder on our datastore where these data are stored. It may be that these could be the same where appropriate but we will have people use our metadata editor and register those records with NKN who may not have their data stored with us. 
Ed will probably be better able to give input to this one since he knows how the geoportal works now to generate uuids and also about what ISO required. The fileidentifier for the metadata file needs to identify a "namespace", ours in previous examples in "nkn: uuid"
Here is a good explanation i found:
One of the ironic aspects of the ISO 19115 is that the identifiers for metadata records (/gmi:MI_Metadata/gmd:fileIdentifier/gmd:characterString and /gmi:MI_Metadata/gmd:parentIdentifier/gmd:characterString) are characterStrings rather than MI_Identifiers. In order to help ensure uniqueness these strings should include a namespace and a code guarenteed to be unique in that namespace. For example:

<gmd:fileIdentifier>
<gco:CharacterString>gov.noaa.class:AERO100</gco:CharacterString>
</gmd:fileIdentifier>.

In this case, gov.noaa.class is a namespace, and AERO100 is a code guaranteed to be unique in that namespace. In this case, the code is meaningful to the data provider. Creating meaningful identifiers that are unique over a large collection can many times be difficult. It might make sense to consider using UUIDs for file names and identifiers, although this takes some getting used to.

**Comment by mguarinello** [comment]
We need a way to indicate that the oid created by the mongo db is a unique idea within our nkn "namespace" 
Other records we have in the geoportal have "nkn:" before the UUID string. "nkn:" indicates the namespace. We may need to distinguish between UUIDs generated in geoportal and ones created in mdedit by the mongo db.
I think we should ask Ed on this one.

**Comment by mtpain** [comment]
Can this be done on the XML generation/XSLT side? Which if any cases will geoportal generate conflicting UUIDs? Could this be a non-issue if, say, the existing geoportal UUIDs have dashes and the mongo ones don't?

**Comment by mguarinello** [comment]
This one is definitely a question for Ed. It would probably have to be a php script or other script that would create the uuid.
For the ISO standard you can have one identifier for the metadata file itself and another one for the data itself. I am not sure how geoportal treats these.
Maybe we just need a different name space for metadata records created with our editor. So something more than "nkn:"

**Comment by flathers** [comment]
The unique identifiers that we are using in the portal are Type 4 UUIDs.  Any procedural language should have a library that allows it to generate them.  XSLT, being a functional language, does not have that capability without adding procedural extensions.  So it would be possible to do it there, but probably easier to do almost anywhere else.

If we can stick with Type 4 UUIDs, we probably don't have to worry about conflicting IDs being created by different applications--they are designed to be statistically unlikely to be repeated randomly.

**Comment by mtpain** [comment]
We can just use Python's standard library [UUID](https://docs.python.org/2/library/uuid.html) module to generate it, and it will be included in tag `uuid` in base tag of the generic XML, e.g. `<uuid>9789dff3-7772-40c6-82b5-9b0031893d55</uuid>`. We can put it where it's supposed to go with XSLTs.

**Comment by mtpain** [comment]
I assigned this to myself and changed the title so that this issue will be closed when the generic xml contains the UUID generated by Mongo on creation of a new record.

**Comment by mtpain** [comment]
This will be closed when we generate UUID4 for the objectID

**Comment by mtpain** [comment]
We were going to use UUID4 because we thought that was required for DataONE. But according to the DataONE documentation linked below, it appears the only restrictions on a UUID are:

> An identifier (PID) in the DataONE system that is used to uniquely and globally identify an object. Identifiers can not be reused 
> once assigned. Identifiers can not be deleted from the DataONE system.Identifiers are represented by a Unicode string of 
> printable characters, excluding whitespace. All representations of identifiers must be encoded in 7-bit ASCII or UTF-8.

> Identifiers have a maximum length of 800 characters, and a variety of other properties designed for preservation and longevity. 
> Some discussion on this is described in the PID documentation and in decision ticket 577.

So let's just use `nkn_editor:` prepended to the ObjectID generated by Mongo  as the [Persistent Unique Identifier](http://jenkins-1.dataone.org/jenkins/job/API%20Documentation%20-%20trunk/ws/api-documentation/build/html/glossary.html#term-25).

### Links

* [Identifiers in DataONE](http://jenkins-1.dataone.org/jenkins/job/API%20Documentation%20-%20trunk/ws/api-documentation/build/html/design/PIDs.html#identifiers-in-dataone) and 
* [XML-specific DataONE Identifier documentation](http://jenkins-1.dataone.org/jenkins/job/API%20Documentation%20-%20trunk/ws/api-documentation/build/html/apis/Types.html#Types.Identifier)
