### ISSUE TITLE
Temporal Extent- change from date to date/time format

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#46]
Enable entry of time along with date for both the start and end entries for temporal extent. Probably have it default to 00:00:00 and then folks can edit it from there. Overall format would be MO/DY/YEAR HH:MM:SS.
This should still work with the xslt as is, but I will need to confirm once the fields are set.

**Comment by flathers** [comment]
Just a note, the ISO schema will enforce ISO 8601 time formats on the date/time field.  So something like 2015-07-16T1629 would express the time right now for me.  If you leave off a time zone, the time is assumed to be 'local time', although the locale is ambiguous here (locale of researcher or data? what if data cross multiple time zones [as they frequently might in Idaho?]).

So far in our catalog, I don't believe anyone has ever entered start/end times for their data.  It might happen, but this is a case where I wonder if there is enough user demand for the feature to justify adding time controls and time zone options and so on.

**Comment by mtpain** [comment]
I'm planning on having the time format be the full ISO since the standard practice is for times to be stored in GMT and then translated for users in whatever time zone.

The time in the generic XML will be, e.g., 2010-01-26T17:01:14.000Z

**Comment by mguarinello** [comment]
It will also show up as 2012-05-27T00:18:17.000Z in the ISO XML, the format Matt mentions above.

@flathers will this works?

**Comment by flathers** [comment]
That works, although you have to make sure that the element name in ISO XML is gco:DateTime rather than gco:Date, which is the default.  Also, the original ISO 19115 doesn't support gco:DateTime, so if you want to output a record in that format, you'll have to lose the time.  I don't know that it's meaningful to include time to the precision of thousandths of a second, but it shouldn't matter.

**Comment by mguarinello** [comment]
Thanks @flathers. I was using <gml:beginPosition>, as in the Challis Lidar ISO record. Do I need to change that or to include another tag level for gco:DateTime?

**Comment by flathers** [comment]
@mguarinello Oh, yes, if you want to use gml:beginPosition and gml:endPosition, those support ISO date and time.

**Comment by mguarinello** [comment]
Great. Closing this issue.
