### ISSUE TITLE
Spatial extent- Auto-complete based on State, County, City input

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#47]
Allow users to select/input state, county, city as spatial extent and have the application auto-complete the lat/lon bounds based on that input.
Is there some kind of service online that generates these coordinates?
I will look into initially.

**Comment by mtpain** [comment]
Couldn't resist checking on this. 

Looks like google has us covered: https://developers.google.com/maps/documentation/geocoding/

Here's a web app that demos it: http://www.mapdevelopers.com/geocode_bounding_box.php

**Comment by mguarinello** [comment]
You beat me to it! I was looking forward to checking this one out too.

**Comment by mtpain** [comment]
my bad... you can look into implementing it in [Python](https://googlemaps.github.io/google-maps-services-python/docs/2.2/) or [JavaScript](https://developers.google.com/maps/documentation/javascript/geocoding)  :)

**Comment by mguarinello** [comment]
No worries. I think this will be a fun one to implement. I will work on it as a 'reward' for getting other parts done. Thanks!

**Comment by mguarinello** [comment]
Success so far using https://geocoder.readthedocs.org/en/stable/api.html#forward-geocoding
have a python script on branch geocode that works. now need to figure out how to put into mdedit workflow
