### ISSUE TITLE
Metadata time stamp

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#5]
Create a time stamp for each time the metadata record is saved. Write this result to the editor-generated xml. Also make it visible on the user's view when the user wants to see a list of the metadata they've created at the date it was last updated.

**Comment by mtpain** [comment]
I'm thinking we could just have the "last updated date" show up when a user goes to edit, and if a user submits edits, that last updated date becomes the current date/time.

**Comment by mguarinello** [comment]
Exactly what I was thinking.
The user should not be able to edit the date in this field. The editor should automatically stamp this field with the current date and it is committed once the user submits the web form. Once the XSLT process runs again (on an update) the old date will be updated with the new one.

**Comment by mtpain** [comment]
Fixed with commit 4a3677fea4b35c05547c283628cb6f5795b31fc3
