### ISSUE TITLE
Enable DOI request and admin moderation process

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#50]
Enable the user not only to submit/publish to NKN but also the option to Request a DOI to be issued for the dataset by NKN. This would somehow need to go to a list somewhere or to create tickets in our work assignment system.

Will need to include instructions to help users answer "Is your data ready for publication with a DOI?"
For example it should be complete, permanent, and immutable.

**Comment by mguarinello** [comment]
Important related info:
from DOI list-serv Matt Jones (NCEAS)
The Force 11 Joint Declaration of Data Citation Principles [1] addresses this. specifically, the principle 7 states:

7. Specificity and Verifiability 
Data citations should facilitate identification of, access to, and verification of the specific data that support a claim.  Citations or citation metadata should include information about provenance and fixity sufficient to facilitate verfiying that the specific timeslice, version and/or granular portion of data retrieved subsequently is the same as was originally cited.

I interpret that to mean that, if an identifier represents the means to find a cited data set, then it should point at the specific data version and subset that were used.  Within the KNB, we issue new DOIs when a change has happened, and record that the new DOI is a newer version of the original, clearly showing the revision history for people that access the citations.

[1] https://www.force11.org/group/joint-declaration-data-citation-principles-final

**Comment by flathers** [comment]
The same is true, in principle, for the portal itself.  Once a data set is published, we don't allow alterations; any revised data would be given a new GUID and published as a new record.  The exception is for retractions--if data need to be retracted for some reason, we will remove the data but leave the metadata record, updated to notify users of the retraction and its reasons.

**Comment by mguarinello** [comment]
Consider whether or not we want to have a DOI moderator (such as Marisa for MILES records)
