### ISSUE TITLE
coordinate system - issue when we get to FGDC XSLT

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#51]
Figure out how ISO captures coordinate system and if projected coordinate systems units are ever used for the bounding extent.

Change issue when know about how to add field

**Comment by flathers** [comment]
I believe that the only way mentioned in the standard is geographic coordinates (lat/long) expressed as decimal degrees.  In fact, in the standard, they specifically say 'This is only an approximate reference so specifying the coordinate reference system is unecessary.'

That's for the bounding box in the extent fields.  There's also a 'referenceSystemInfo' element, but that's only for describing the spatial reference of the data, not the metadata bounding box.

**Comment by mtpain** [comment]
@mguarinello close?

**Comment by mguarinello** [comment]
Thanks @flathers. Thank you for confirming my hunch that only lat/lon as decimal degrees is used. @mtpain I will add a little bit to the instructions for the spatial extent field in the Excel Design Doc on master. Once you have added those instructions, go ahead and close this issue. Thanks team!

**Comment by mguarinello** [comment]
I was all set to add to the instructions and close this issue, and then I recalled that we talked about offering the results of the editor as ISO, FGDC, and maybe Esri formats. The FGDC standard does include fields for geographic coordinate system and projection used.
So.....do we continue to build the editor only for ISO and rely on transforms for FGDC and perhaps have missing fields? Or do we add fields for geographic coord syst and projection and only use in the XSLT transform for FGDC? @flathers what do you think will work best?

**Comment by flathers** [comment]
Good point.  I have seen FGDC metadata that uses UTM to describe its bounding area, although it's rare in my experience.  I think most people are using WGS84 to describe bounding boxes right now?

If we only allow lat/long in decimal degrees to be entered into the editor, we could assume that the spatial reference for that is WGS84, and, keeping in mind that the bounding box is usually pretty approximate anyway, if we wanted to generate an FGDC or ESRI record, we could output the lat/long of the bounding box with a pre-made WGS84 spatref block.

How does that sound?

**Comment by mguarinello** [comment]
That seems reasonable to me.

**Comment by mguarinello** [comment]
I am moving this to Portal Integration. This will need to be an issue when we develop and XSLT for FGDC view.
