### ISSUE TITLE
Link metadata record to uuid of dataset in NKN's datastore

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#6]
Some metadata records will be linked to data that is already in the NKN datastore or it will be uploaded to the datastore in the future. Users should have the option to upload data when they create metadata with our editor (in the future). 

There needs to be a way to grab the uuid of associated data from the datastore and use it for the <gmd:dataSetURI> tag in the metadata.

Somehow the uuid of the data and the uuid of the metadata need to "recognize" each other.

**Comment by mtpain** [comment]
This is similar to #4, except #4 just requires we create a UUID for each metadata record. It turns out a UUID is automatically generated by MongoDB, we just need to add that to the generic XML that will be XSLT'd into ISO for storage in NKN's geoportal.
Then when our service that checks for updates from editor-generated metadata ingests ISO metadata from the editor, the UUID will come along with it.

**Comment by mguarinello** [comment]
I think there may be some misunderstanding here. The uuid to link to the record in our datastore needs to be linked to the system NKN's portal uses to set the uuid. Ed knows more.

**Comment by flathers** [comment]
Yes, we'll definitely need to take whatever UUID is generated and insert it into the geoportal database if we want to be able to search the records from there.  But that's not too hard.  It's a postgresql database, and I've worked with altering the tables from custom software before.

**Comment by mtpain** [comment]
OK, thanks, Ed. Just to be clear:

1. Marisa transfers the UUID from the generic XML to the ISO UUID field via XSLT
2. You would write some software to extract it and update the postgresql database? Or maybe you already have that written somewhere?

**Comment by flathers** [comment]
I had forgotten that we were planning to incorporate these metadata into the portal by harvesting the folder periodically.  Now I need to think about this again.

**Comment by mtpain** [comment]
Per team meeting, this is not an issue: we can just use the Mongo-generated Object ID or a UUID4.
