### ISSUE TITLE
Keywords parsing

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#8]
Our editor process needs to be able to identify words separated by commas in the entry form as separate entries.

This needs to either be on the mdedit end or in the XSLT (not sure yet if this is possible).

**Comment by mtpain** [comment]
When you say keywords, you mean this section, right?

```xml
<gmd:descriptiveKeywords>
        <gmd:MD_Keywords>
          <gmd:keyword>
            <gco:CharacterString>keyword 1</gco:CharacterString>
          </gmd:keyword>
          <gmd:keyword>
            <gco:CharacterString>MILES</gco:CharacterString>
          </gmd:keyword>
          <gmd:keyword>
            <gco:CharacterString>EPSCoR</gco:CharacterString>
          </gmd:keyword>
          <gmd:keyword>
            <gco:CharacterString>IIA-1301792</gco:CharacterString>
          </gmd:keyword>
          <gmd:type>
            <gmd:MD_KeywordTypeCode codeSpace="ISOTC211/19115" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="theme">theme</gmd:MD_KeywordTypeCode>
          </gmd:type>
        </gmd:MD_Keywords>
      </gmd:descriptiveKeywords>
```

What is this part doing?

```xml
 <gmd:type>
            <gmd:MD_KeywordTypeCode codeSpace="ISOTC211/19115" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="theme">theme</gmd:MD_KeywordTypeCode>
          </gmd:type>
```

**Comment by mguarinello** [comment]
Yes that is the keyword part. Those are the "theme" keywords. There are also "place" keywords. We need to be able to parse both, but keep as separate sections as they are in the mdedit created xml now. The type part I can hard code into the XSLT

**Comment by mtpain** [comment]
For this I'm thinking we can store the keywords as a list in Mongo and make sure the generic xml is formatted so that the XSLT can do the appropriate transformation.

**Comment by mguarinello** [comment]
That will work as long as there are two lists: theme and place (See above comment)

**Comment by mtpain** [comment]
Right, there will be two keywords lists. The theme one would look something like this:

```xml
<theme_keywords type="list">
   <item type="str">
        desert
   </item>
   <item type="str">
       wildlife
   </item>
   <item type="str">
       lizards
   </item>
</theme_keywords>
```

And a similar one for `place_keywords`.

**Comment by mguarinello** [comment]
perfect


Marisa Guarinello
Environmental Data Manager
MILES EPSCoR Project
Northwest Knowledge Network
University of Idaho, Office of Research & Economic Development
mguarinello@uidaho.edu
208-885-5044

**Comment by mguarinello** [comment]
need to figure out in XSLT how to do a "for loop" since each keyword has the same tag "item"- existing method I am using doesn't work

**Comment by mguarinello** [comment]
Figured out. Changes to generation of generic xml required. Included in comments on open pull request for angular #34

**Comment by mtpain** [comment]
Need to change lists of strings from

```xml
<theme_keywords type="list">
   <item type="str">
        desert
   </item>
   <item type="str">
       wildlife
   </item>
   <item type="str">
       lizards
   </item>
</theme_keywords>
```

to 

```xml
<theme_keywords type="list">
   ...
   <item>
       <word type="str">
       lizards
      </word>
   </item>
</theme_keywords>
```

**Comment by mtpain** [comment]
Here's an example of the current angular branch XML, will this work?

```xml
<thematic_keywords type="list">
    <item type="dict">
        <word type="str">water</word>
    </item> 
    <item type="dict">
        <word type="str">delta tuna melta</word>
    </item>
</thematic_keywords>
```

**Comment by mguarinello** [comment]
Yes it should.
I will pull angular now and test.


Marisa Guarinello
Environmental Data Manager
MILES EPSCoR Project
Northwest Knowledge Network
University of Idaho, Office of Research & Economic Development
mguarinello@uidaho.edu
208-885-5044

**Comment by mguarinello** [comment]
This is now fixed in the generic xml to match what is needed to make the xslt work. Closing.
