### ISSUE TITLE
Select from a list: status and topic category

### ISSUE THREAD

**Issue by mtpain** [northwest-knowledge-network/mdedit#9]
As outline in the Excel design doc.

**Comment by mguarinello** [comment]
just updated the values for status in the design doc. please use the exact wording below. thanks!
they are also here:
completed, continually updated, in process, planned, needs to be generated or updated, stored in an offline facility, no longer valid

**Comment by mguarinello** [comment]
The selection entries need to appear as indicated in my comment and in the Design document- including capitalization as indicated. For this field they should be lower case. The same is true of the data update frequency field.
