### ISSUE TITLE
going to frontend/#/iso, editing, and save draft results in DC record created and saved

### ISSUE THREAD

**Issue by mtpain** [northwest-knowledge-network/mdedit#91]
To reproduce this bug, start up the servers `./startup.py run` and then go directly to [http://localhost:8000/frontend/#/iso](http://localhost:8000/frontend/#/iso). Create a fake record, hit save, and check the schema type in the dropdown list.

I get that it is a Non-Dataset (Dublin Core) schema type. Can't figure out how it's happening.  We don't have to keep this out of the dcFix merge, but please add this to the list of cleanup items.

**Comment by mguarinello** [comment]
this is fixed in current PR #99, closing this issue
