### ISSUE TITLE
deleting current dublin core edited record leads to next "dublin core" record to be saved as iso

### ISSUE THREAD

**Issue by mtpain** [northwest-knowledge-network/mdedit#92]
This is like #91 where it would appear one was editing an iso record, but it gets saved as dublin. Except now it's reversed, and to recreate this:

1. go to http://localhost:8000/frontend
2. click on "create new non-dataset record"
3. save a fake record
4. delete the record you just saved
5. You'll be on the #/dublin view with the fields empty. Fill in some fields and save a new record.
6. Inspect the record in the "Load or Delete..." dropdown: it will say the datatype is iso but the form is clearly dublin

I'm assigning @mguarinello because maybe you can figure this out since you've been working with the dublin/iso stuff. But it may be complicated by the messiness in the controllers and services.

**Comment by mguarinello** [comment]
fixed this. in my current JanFix branch
